"use client";

import { FormEvent, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Category = "Restaurants" | "Supermarket" | "Clothes & Lifestyle";
type Product = { id: string; name: string; store: string; category: Category; description: string; price: number; image?: string; label?: string };
type CartLine = Product & { quantity: number };
const products: Product[] = [
  { id: "burger", name: "Classic Cheeseburger", store: "Burger Corner", category: "Restaurants", description: "Beef, cheddar, lettuce and tomato", price: 12.99, image: "/assets/images/burger-one.png" },
  { id: "pizza", name: "Garden Pizza", store: "Piazza Pizza", category: "Restaurants", description: "Mozzarella, tomato and fresh basil", price: 14.5, image: "/assets/images/pizza-one.png" },
  { id: "bowl", name: "Fresh Summer Bowl", store: "Garden Kitchen", category: "Restaurants", description: "Greens, avocado and roasted vegetables", price: 10.5, image: "/assets/images/salad.png" },
  { id: "avocado", name: "Avocado Pack", store: "Green Basket Market", category: "Supermarket", description: "Four fresh ready-to-eat avocados", price: 5.25, image: "/assets/images/avocado.png" },
  { id: "tomatoes", name: "Vine Tomatoes", store: "Green Basket Market", category: "Supermarket", description: "Fresh local tomatoes, 1 kg", price: 3.75, image: "/assets/images/tomatoes.png" },
  { id: "cheese", name: "Cheese Selection", store: "Daily Pantry", category: "Supermarket", description: "Three artisan cheese portions", price: 8.5, image: "/assets/images/cheese.png" },
  { id: "shirt", name: "Everyday T-Shirt", store: "Urban Thread", category: "Clothes & Lifestyle", description: "Soft cotton, available in multiple colors", price: 18, label: "Style" },
  { id: "hoodie", name: "City Hoodie", store: "Urban Thread", category: "Clothes & Lifestyle", description: "Relaxed fit fleece hoodie", price: 42, label: "Wear" },
  { id: "socks", name: "Comfort Socks", store: "Little Things", category: "Clothes & Lifestyle", description: "Three-pair everyday cotton set", price: 9.5, label: "Daily" },
];
const categories: ("All" | Category)[] = ["All", "Restaurants", "Supermarket", "Clothes & Lifestyle"];
const money = (value: number) => `$${value.toFixed(2)}`;

export default function Home() {
  const [category, setCategory] = useState<(typeof categories)[number]>("All");
  const [cart, setCart] = useState<CartLine[]>([]); const [cartOpen, setCartOpen] = useState(false); const [checkout, setCheckout] = useState(false);
  const [address, setAddress] = useState(""); const [orderComplete, setOrderComplete] = useState(false); const [phone, setPhone] = useState(""); const [note, setNote] = useState(""); const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null); const [locationText, setLocationText] = useState(""); const [checkoutMessage, setCheckoutMessage] = useState(""); const [sending, setSending] = useState(false);
  const visible = useMemo(() => category === "All" ? products : products.filter((product) => product.category === category), [category]);
  const count = cart.reduce((sum, line) => sum + line.quantity, 0); const total = cart.reduce((sum, line) => sum + line.price * line.quantity, 0); const store = cart.length ? [...new Set(cart.map((line) => line.store))].join(", ") : "";
  function add(product: Product) { setCart((current) => { const existing = current.find((line) => line.id === product.id); return existing ? current.map((line) => line.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { ...product, quantity: 1 }]; }); }
  function remove(id: string) { setCart((current) => current.filter((line) => line.id !== id)); }
  function findLocation() { if (!navigator.geolocation) { setLocationText("Location is not supported in this browser. Please enter your address."); return; } setLocationText("Finding your location..."); navigator.geolocation.getCurrentPosition((position) => { setLocation({ lat: position.coords.latitude, lng: position.coords.longitude }); setLocationText("Location added to your delivery order."); }, () => setLocationText("We could not get your location. Please enter your address."), { enableHighAccuracy: true, timeout: 10000 }); }
  async function placeOrder(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!cart.length) return; setSending(true); setCheckoutMessage(""); try { const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.assign("/auth"); return; } const { data: order, error: orderError } = await supabase.from("orders").insert({ customer_id: user.id, store, category: [...new Set(cart.map((line) => line.category))].join(", "), delivery_address: address, phone, customer_note: note || null, location_lat: location?.lat ?? null, location_lng: location?.lng ?? null, total }).select("id").single(); if (orderError) throw orderError; const { error: itemsError } = await supabase.from("order_items").insert(cart.map((line) => ({ order_id: order.id, product_name: line.name, unit_price: line.price, quantity: line.quantity }))); if (itemsError) throw itemsError; setCart([]); setCheckout(false); setCartOpen(false); setAddress(""); setPhone(""); setNote(""); setLocation(null); setOrderComplete(true); setCheckoutMessage(""); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (error) { setCheckoutMessage(error instanceof Error ? error.message : "Your order could not be placed."); } finally { setSending(false); } }
  return <main>
    <header className="header"><a href="#top" className="brand"><i>F</i>oodieFly</a><nav><a href="#shops">Shops</a><a href="#how">How it works</a><a href="/dashboard">My account</a></nav><div className="headerActions"><a className="loginLink" href="/auth">Sign in</a><button className="cartButton" onClick={() => { setCartOpen(true); setCheckout(false); }}>Cart <span>{count}</span></button></div></header>
    <section className="hero marketplaceHero" id="top"><div className="heroCopy"><p className="eyebrow">ONE APP. MANY EVERYDAY NEEDS.</p><h1>Anything you need,<br/><em>delivered to you.</em></h1><p className="intro">Order from restaurants, supermarkets, and local lifestyle stores in one easy place.</p><a className="primary" href="#shops">Browse stores <b>-&gt;</b></a><p className="rating"><strong>Fast local delivery</strong><span> * * * </span><small>from nearby stores to your door</small></p></div><div className="heroArt"><div className="circle"/><img className="heroFood" src="/assets/images/burger-two.png" alt="FoodieFly delivery"/><div className="delivery"><b>Restaurant to retail</b><small>one checkout, one delivery</small></div></div></section>
    <section className="marketCategories" id="shops"><p className="eyebrow">SHOP BY CATEGORY</p><div className="categoryCards">{categories.slice(1).map((item) => <button key={item} onClick={() => { setCategory(item); document.querySelector("#products")?.scrollIntoView({ behavior: "smooth" }); }}><strong>{item === "Restaurants" ? "Restaurants" : item === "Supermarket" ? "Supermarket" : "Clothes & Lifestyle"}</strong><small>{item === "Restaurants" ? "Fresh meals from demo local kitchens" : item === "Supermarket" ? "Groceries and pantry essentials" : "Clothes and everyday finds"}</small><span>{item === "Restaurants" ? "Meals" : item === "Supermarket" ? "Groceries" : "Style"}</span></button>)}</div></section>
    <section className="filters">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</section>
    <section className="menu" id="products"><div className="sectionTitle"><div><p className="eyebrow">DEMO LOCAL STORES</p><h2>{category === "All" ? "Shop what you need" : category}</h2></div><a href="/dashboard">Track my orders -&gt;</a></div><div className="grid marketplaceGrid">{visible.map((product) => <article className="card" key={product.id}>{product.image ? <div className="mealImage"><img src={product.image} alt={product.name}/></div> : <div className="productPlaceholder">{product.label}</div>}<small className="storeName">{product.store}</small><h3>{product.name}</h3><p>{product.description}</p><div className="cardBottom"><b>{money(product.price)}</b><button aria-label={`Add ${product.name}`} onClick={() => add(product)}>+</button></div></article>)}</div></section>
    <section className="how" id="how"><div><p className="eyebrow">ONE SIMPLE FLOW</p><h2>Shop, locate, deliver.</h2></div><ol><li><span>01</span><b>Choose a local store</b><p>Browse meals, groceries and everyday essentials.</p></li><li><span>02</span><b>Add delivery details</b><p>Share your address, phone number and optional map location.</p></li><li><span>03</span><b>Track your order</b><p>A nearby delivery driver accepts and delivers your order.</p></li></ol></section>
    <footer><a href="#top" className="brand"><i>F</i>oodieFly</a><p>Demo stores are fictional and ready to be replaced with real partners.</p><small>2026 FoodieFly</small></footer>
    {cartOpen && <><div className="overlay" onClick={() => { setCartOpen(false); setCheckout(false); }}/><aside className="cartPanel"><div className="cartHead"><h2>{checkout ? "Delivery details" : "Your order"}</h2><button onClick={() => { setCartOpen(false); setCheckout(false); }}>x</button></div>{checkout ? <form className="checkoutForm" onSubmit={placeOrder}><p className="checkoutStore">Ordering from <b>{store}</b></p><label>Delivery address<input required value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Building, street, city"/></label><label>Phone number<input required value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="03 123 456"/></label><button type="button" className="locationButton" onClick={findLocation}>Use my current location</button>{locationText && <small className="locationText">{locationText}</small>}<label>Delivery note <em>(optional)</em><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Apartment number, entrance, or other details"/></label><div className="total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary checkout" disabled={sending}>{sending ? "Placing order..." : "Place order"}</button></form> : <>{cart.length ? <div>{cart.map((line) => <div className="cartLine" key={line.id}><span><b>{line.name} x {line.quantity}</b><small>{money(line.price)} each</small></span><button onClick={() => remove(line.id)}>Remove</button></div>)}</div> : <p className="empty">Your cart is empty. Choose a store to begin.</p>}<div className="total"><span>Total</span><strong>{money(total)}</strong></div>{checkoutMessage && <p className="cartMessage">{checkoutMessage}</p>}<button className="primary checkout" disabled={!cart.length} onClick={() => { setCheckout(true); setCheckoutMessage(""); }}>Continue to delivery details</button></>}</aside></>}\n    {orderComplete && <><div className="overlay successOverlay"/><section className="successDialog" role="dialog" aria-modal="true"><button type="button" className="successClose" onClick={() => setOrderComplete(false)}>x</button><p className="eyebrow">ORDER CONFIRMED</p><h2>Your order was received.</h2><p>Thank you! Your delivery details are saved and a delivery driver can now accept the order.</p><button type="button" className="primary" onClick={() => { setOrderComplete(false); window.location.assign("/"); }}>Back to main page</button></section></>}
  </main>;
}