"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Role = "customer" | "delivery";
type Profile = { full_name: string | null; role: Role };
type Order = { id: string; store: string; category: string; delivery_address: string; phone: string; customer_note: string | null; total: number; status: "pending" | "accepted" | "picked_up" | "on_the_way" | "delivered"; location_lat: number | null; location_lng: number | null; created_at: string; order_items: { product_name: string; quantity: number; unit_price: number }[] };
const statusText: Record<Order["status"], string> = { pending: "Waiting for a driver", accepted: "Driver assigned", picked_up: "Picked up", on_the_way: "On the way", delivered: "Delivered" };
const money = (value: number) => `$${Number(value).toFixed(2)}`;
export default function RoleDashboard({ requiredRole }: { requiredRole: Role }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [userId, setUserId] = useState(""); const [ready, setReady] = useState(false); const [message, setMessage] = useState(""); const [refreshing, setRefreshing] = useState(false);
  const loadOrders = useCallback(async (id: string, showRefresh = false) => { if (showRefresh) setRefreshing(true); let query = supabase.from("orders").select("id, store, category, delivery_address, phone, customer_note, total, status, location_lat, location_lng, created_at, order_items(product_name, quantity, unit_price)").order("created_at", { ascending: false }); if (requiredRole === "customer") query = query.eq("customer_id", id); else query = query.in("status", ["pending", "accepted", "picked_up", "on_the_way"]); const { data, error } = await query; if (error) setMessage(error.message); else setOrders((data ?? []) as Order[]); if (showRefresh) setRefreshing(false); }, [requiredRole]);
  useEffect(() => { async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) return window.location.replace("/auth"); const { data, error } = await supabase.from("profiles").select("full_name, role").eq("id", user.id).single(); if (error || !data) return window.location.replace("/auth"); if (data.role !== requiredRole) return window.location.replace(data.role === "delivery" ? "/dashboard/delivery" : "/dashboard/customer"); setProfile(data as Profile); setUserId(user.id); await loadOrders(user.id); setReady(true); } load(); }, [loadOrders, requiredRole]);
  useEffect(() => { if (!userId) return; const interval = window.setInterval(() => loadOrders(userId), 5000); return () => window.clearInterval(interval); }, [loadOrders, userId]);
  async function updateOrder(order: Order, next: Order["status"]) { setMessage(""); const change = next === "accepted" ? { driver_id: userId, status: next } : { status: next }; const { error } = await supabase.from("orders").update(change).eq("id", order.id).eq("status", order.status); if (error) setMessage(error.message); else { setMessage(`Order updated: ${statusText[next]}.`); await loadOrders(userId); } }
  const available = useMemo(() => orders.filter((order) => order.status === "pending"), [orders]); const active = useMemo(() => orders.filter((order) => order.status !== "pending"), [orders]);
  function card(order: Order, driver: boolean) { return <article className="orderCard" key={order.id}><div className="orderTop"><div><span>{order.category}</span><h2>{order.store}</h2></div><b className={`status ${order.status}`}>{statusText[order.status]}</b></div><ul>{order.order_items?.map((item, index) => <li key={`${item.product_name}-${index}`}>{item.quantity} x {item.product_name}</li>)}</ul><p><b>Delivery:</b> {order.delivery_address}</p>{driver && <><p><b>Phone:</b> <a href={`tel:${order.phone}`}>{order.phone}</a></p>{order.customer_note && <p><b>Note:</b> {order.customer_note}</p>}{order.location_lat && order.location_lng && <a className="mapLink" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${order.location_lat},${order.location_lng}`}>Open route in Google Maps</a>}</>}<div className="orderActions"><strong>{money(order.total)}</strong>{driver && order.status === "pending" && <button onClick={() => updateOrder(order, "accepted")}>Accept order</button>}{driver && order.status === "accepted" && <button onClick={() => updateOrder(order, "picked_up")}>Mark picked up</button>}{driver && order.status === "picked_up" && <button onClick={() => updateOrder(order, "on_the_way")}>Start delivery</button>}{driver && order.status === "on_the_way" && <button onClick={() => updateOrder(order, "delivered")}>Mark delivered</button>}</div></article>; }
  if (!ready) return <main className="loading">Checking your account permissions...</main>; if (!profile) return null; const driver = requiredRole === "delivery";
  return <main className="dashboard"><header className="header"><a className="brand" href="/"><i>F</i>oodieFly</a><button className="signOut" onClick={async () => { await supabase.auth.signOut(); window.location.replace("/auth"); }}>Sign out</button></header><section><div className="dashboardIntro"><div><p className="eyebrow">{driver ? "DELIVERY DRIVER PORTAL" : "CUSTOMER ACCOUNT"}</p><h1>Hello, {profile.full_name || "FoodieFly friend"}.</h1><p className="intro">{driver ? "Accept available orders, then update each delivery as you go." : "Your current and past orders appear here."}</p></div>{driver && <button className="refreshButton" onClick={() => loadOrders(userId, true)} disabled={refreshing}>{refreshing ? "Refreshing..." : "Refresh orders"}</button>}</div>{message && <p className="dashboardMessage">{message}</p>}{driver ? <div className="driverColumns"><div><div className="driverHeading"><h2>Available orders</h2><span>{available.length}</span></div><p className="driverHint">Accept an order to add it to your active deliveries.</p><div className="ordersList driverOrders">{available.length ? available.map((order) => card(order, true)) : <div className="emptyState">No unassigned orders right now. This list refreshes every 5 seconds. If it stays empty, make sure a Customer account successfully placed the order.</div>}</div></div><div><div className="driverHeading"><h2>My active deliveries</h2><span>{active.length}</span></div><p className="driverHint">Update the status after every delivery step.</p><div className="ordersList driverOrders">{active.length ? active.map((order) => card(order, true)) : <div className="emptyState">You have no active deliveries yet.</div>}</div></div></div> : <div className="ordersList">{orders.length ? orders.map((order) => card(order, false)) : <div className="dashboardCard"><span>CUSTOMER</span><h2>No active orders yet</h2><p>Browse the stores to place your first order.</p><a className="primary" href="/">Explore stores</a></div>}</div>}</section></main>;
}